### PR TITLE
Fix imports to work in numba 0.50.0

### LINKED ISSUE #1: Numba 0.50.0 does not work with this package
The renaming of builtin numba modules leads to the following issue:
```
>>> import numba_passthru
ImportError: cannot import name 'cgutils' from 'numba' 
```

### PR DESCRIPTION
**Pull request by eric-wieser**
This also silences warnings in numba 0.49.0

Closes #1

### CODE REVIEW

**Comment by asodeur** [comment]
Thank you for the pull request. I could not test on `numba>0.48` as our internal CI is not updated, yet. I'll merge anyway. I'd expect we will make the switch to 0.48 some time before end of the month.
